name: repo_viewer
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  auto_route: ^6.2.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.1.1
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.4
  http: ^0.13.6
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^6.0.7096
  oauth2: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.15
  sembast: ^3.4.6+1
  shimmer: ^3.0.0
  webview_flutter: ^4.2.2
  material_floating_search_bar: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  auto_route_generator: ^6.2.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
